### ISSUE TITLE
replace TestUtils with portable-scala-reflect

### ISSUE THREAD

**Issue by SethTisue** [monix/minitest#27]
thanks to scala-js/scala-js@a22886bdacb80bcac749cb234fb1eac134552047 (part of https://github.com/scala-js/scala-js/pull/3356), minitest needs the same treatment that utest got in https://github.com/lihaoyi/utest/pull/178 /cc @sjrd

this turned up in the Scala 2.12 community build at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3520/consoleFull

```
[minitest] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/minitest-3135a316c87d6520199f60a7113aa9824e4dcd6b/jvm_js/src/main/scala/minitest/Platform.scala:20:12: object scalajs is not a member of package org
[minitest] [error] import org.scalajs.testinterface.TestUtils
[minitest] [error]            ^
```

**Comment by sjrd** [comment]
https://github.com/monix/minitest/pull/28
