### ISSUE TITLE
Running tests in IDE

### ISSUE THREAD

**Issue by mkotsbak** [monix/minitest#3]
Is it possible to run the tests though an IDE like IntelliJ? It has of course not any support internal, but is it possible to get it to trigger what sbt does?

**Comment by lukestephenson** [comment]
+1.  I'm trying to contribute to monix.  Not being able to debug tests in intellij is really impacting my ability to understand and learn the code.

**Comment by alexandru** [comment]
@lukestephenson you can already debug tests in IntelliJ.

Start your SBT like this:
```
sbt -jvm-debug 5005
```

It will say:
```
Listening for transport dt_socket at address: 5005
```

Then in IntelliJ IDEA do: Run, then Debug..., then create a new Remote configuration, using the 5005 port, specified above. This will make IntelliJ IDEA connect to that remote port and do debugging on it.

You can then set breakpoints and upon running the tests, it will hit them ;-)
