### ISSUE TITLE
Publish for ScalaJS 1.0.0-M8

### ISSUE THREAD

**Issue by fdietze** [monix/minitest#43]
The title says it all. I created the issue to get notified.

**Comment by ekrich** [comment]
This would now be `1.0.0-RC1` support. As suggested in the Scala Native issue.
`export SCALAJS_VERSION=1.0.0-RC1`; sbt

**Comment by mikla** [comment]
+1. Publish for `1.0.0-RC2` also would make sense.

**Comment by mikla** [comment]
I guess there is no way to use `1.13.5` scalacheck  version in `lawsLegacy` as it's not published to Scala.js 1.0

**Comment by nafg** [comment]
Looks like support for scalajs 1 was merged, when will it be published?

**Comment by takayahilton** [comment]
https://github.com/monix/implicitbox/pull/5

**Comment by mathieuleclaire** [comment]
+1. Is publishing for scala-js 1.0 or 1.0.1 is doable ?

**Comment by Avasil** [comment]
Hello, I have released `2.8.1` with ScalaJS 1.0.0 and Scala Native 0.4.0-M2 support. Let me know if there are any issues!
