### ISSUE TITLE
beforeAll/afterAll

### ISSUE THREAD

**Issue by hseeberger** [monix/minitest#7]
Nice library!

As far as I understand, `setUp` and `tearDown` are called for each test. Most time when testing Akka code one want's to create and terminate an `ActorSystem` once for the whole test suite. ScalaTest facilitates this with mixing in `BeforeAndAfterAll`.

Do you think this is something that you also want to consider for minitest?

**Comment by kkafara** [comment]
It would be great to have methods like `setUpSuite` and `tearDownSuite`. I've tried to play with `minitest` code a bit to add it, but I guess it won't be possible without breaking changes.

@alexandru would you consider adding it? - is it worth for me to clean up my changes and submit PR? 😉

**Comment by MansurAshraf** [comment]
+1, this is the only missing feature that is preventing me from ditching scalatest. I would really appreciate it if you could add this

**Comment by alexandru** [comment]
@hseeberger @kkafara @MansurAshraf thanks for your patience.

Due to PR #9 it's in the latest release, version `2.1.0`.
